### ISSUE TITLE
EEPROM initialization: missing information

### ISSUE THREAD

**Issue by iw2lsi** [markqvist/rnodeconfigutil#4]
Hi...

  first of all, thanks a lot for the great project! 
 
   it seems that eeprom initialization requires also to provide model, hardware revision and to generate a signing key... but the User Manual does not explain how to proceed and which values provide for model and hwrev...

In my case (custom board) I had to do something line:

rnodeconf /dev/ttyUSB0 --model a9 --hwrev 1  -k

but I'm sure about the meaning of the provided value ...

                    Giampaolo

**Comment by markqvist** [comment]
I haven't really documented those features since they are not intended for normal users, but only for myself when manufacturing RNodes, and for people who build their own. But here is the general procedure for reference:

- To bootstrap your own boards, you should first generate your own signing key, just run "rnodeconf -k" by itself one time. The key will be saved and used to sign the EEPROM contents of RNodes you have built.
- After that you can flash the firmware and bootstrap the EEPROM in one step with: "rnodeconf /dev/ttyUSB0 --model a9 --hwrev 10". The model option refers to the model, a9 for 820-1020 MHz models, and a4 for 410-525 MHz models. The --hwrev would be a code for your own hardware version.

**Comment by iw2lsi** [comment]
thanks Mark…

  I’ve not yet finished my boards but at least I was able to flash the firmware into the board…

     Giampaolo

Inviato da iPhone

**Comment by markqvist** [comment]
Cool! Wishing you success!
